---
title: "作业11 geo"
author: "krissy"
date: "`r Sys.Date()`"
output: html_document
---
# 作业11-1
1.	根据开发区的地理边界与企业地址坐标，计算出开发区内部的企业数量；计算出开发区1km，3km，5km范围内的企业数量
D:\ZY_r_data\1R_cause\eco_learn_RY\dataALL\assigment_geo 文件夹下面有G132004保定高新技术产业开发区 的4个区块地理信息的txt文件

 krissy
2024-04-08
```{r}
rm(list = ls())
```

```{r}
library(sf) # 用于处理空间数据
library(ggplot2) # 用于绘图

# 读取GeoJSON文件
file_paths <- c(
  "D:/ZY_r_data/1R_cause/eco_learn_RY/dataALL/assigment_geo/G132004保定高新技术产业开发区区块二（实验区）.txt",
  "D:/ZY_r_data/1R_cause/eco_learn_RY/dataALL/assigment_geo/G132004保定高新技术产业开发区区块三（西区）.txt",
  "D:/ZY_r_data/1R_cause/eco_learn_RY/dataALL/assigment_geo/G132004保定高新技术产业开发区区块四（东区）.txt",
  "D:/ZY_r_data/1R_cause/eco_learn_RY/dataALL/assigment_geo/G132004保定高新技术产业开发区区块一（中心区）.txt"
)

# 读取并合并这些文件
develop_area_sf_list <- lapply(file_paths, st_read)
develop_area_combined <- do.call(rbind, develop_area_sf_list)


```

```{r}
# 绘制所有区块的地理边界
ggplot() +
  geom_sf(data = develop_area_combined) +
  theme_minimal() +
  ggtitle("合并后的开发区地理边界")

```




```{r}
library(readr) # 用于读取数据
library(dplyr) # 用于数据处理

# 读取企业地理信息
companies_df <- read_delim("D:/ZY_r_data/1R_cause/eco_learn_RY/dataALL/assigment_geo/hefei.txt", 
                           delim = "\t", 
                           col_names = c("pripid", "lng", "lat", "city"))

# 检查数据并尝试转换为数值类型，同时保留能成功转换的行
companies_df <- companies_df %>%
  mutate(lng = as.numeric(lng),
         lat = as.numeric(lat)) %>%
  filter(!is.na(lng) & !is.na(lat))

# 如果上述步骤仍然导致NA的生成，那么可能需要手动检查数据源以识别问题

# 转换为sf对象
companies_sf <- st_as_sf(companies_df, coords = c("lng", "lat"), crs = 4326)

# 使用开发区sf对象进行空间关系判断
inside_develop_area <- st_within(companies_sf, develop_area_combined, sparse = FALSE)

# 计算在开发区内部的企业数量
num_inside <- sum(inside_develop_area)

# 打印结果
print(paste("位于开发区内部的企业数量:", num_inside))


```







# 作业11-2
2.	画出保定市的四个开发区，以及开发区内的企业

```{r}
library(ggplot2)

# 绘制开发区边界和企业位置
ggplot() +
  geom_sf(data = develop_area_combined, fill = "lightblue", color = "darkblue", size = 0.5, alpha = 0.5) +
  geom_sf(data = companies_sf, color = "red", size = 2, shape = 18) +
  theme_minimal() +
  ggtitle("开发区及企业位置") +
  labs(x = "经度", y = "纬度")

```


# 作业11-3
3.	自学栅格数据处理与可视化，并完成练习题5.4E7



# 作业11-4
4.	自学制作中国地图，“./slides/ChinaMap”，将保定市的所有企业都着点在“保定市”地图上
# 
